"""empty message

Revision ID: 0d1155978d08
Revises: ec300f28cbf6
Create Date: 2017-05-30 11:22:54.488198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1155978d08'
down_revision = 'ec300f28cbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('parties_attendee_id_fkey', 'parties', type_='foreignkey')
    op.drop_column('parties', 'attendee_rating')
    op.drop_column('parties', 'host_rating')
    op.drop_column('parties', 'attendee_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('attendee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('parties', sa.Column('host_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('parties', sa.Column('attendee_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('parties_attendee_id_fkey', 'parties', 'users', ['attendee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
