"""broke out datetime column into date and time

Revision ID: 7c315b75d6cb
Revises: a4446ec1cfc0
Create Date: 2017-05-31 11:57:58.677906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c315b75d6cb'
down_revision = 'a4446ec1cfc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('date', sa.DATE(), nullable=True))
    op.add_column('parties', sa.Column('time', sa.TIME(), nullable=True))
    op.drop_column('parties', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('parties', 'time')
    op.drop_column('parties', 'date')
    # ### end Alembic commands ###
