"""empty message

Revision ID: a4446ec1cfc0
Revises: b42331829911
Create Date: 2017-05-30 13:54:37.022632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4446ec1cfc0'
down_revision = 'b42331829911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('state', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('zipcode', sa.Text(), nullable=True))
    op.drop_column('users', 'header_image_url')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('header_image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'zipcode')
    op.drop_column('users', 'state')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
